Adicionar a versão do Magento no header "User-Agent" para os requests realizados para a API
melhorenvio/magento1 pull request #6
Opened 2020-11-26 19:30 UTC by novapc

**Tipo das modificações:** PATCH.

Este Pull Request adiciona a versão do Magento no header "**User-Agent**" para os requests realizados para a API.

2020-11-30 18:24 UTC, andrevpde90 approved these changes

2020-11-30 19:18 UTC, marcalpizzi requested changes

2020-11-30 19:18 UTC, marcalpizzi commented on NovaPC_Melhorenvio/app/code/community/NovaPC/Melhorenvio/Helper/Data.php
> +			"User-Agent: Magento 1/" . Mage::getVersion(),
Ajustar identação.

2020-12-02 00:01 UTC, marcalpizzi approved these changes

2020-12-02 12:44 UTC, merged